//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snooze.Mspecc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snooze.Mspecc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///   Extensible HTML version 1.0 Frameset DTD
        ///
        ///   This is the same as HTML 4 Frameset except for
        ///   changes due to the differences between XML and SGML.
        ///
        ///   Namespace = http://www.w3.org/1999/xhtml
        ///
        ///   For further information, see: http://www.w3.org/TR/xhtml1
        ///
        ///   Copyright (c) 1998-2002 W3C (MIT, INRIA, Keio),
        ///   All Rights Reserved. 
        ///
        ///   This DTD module is identified by the PUBLIC and SYSTEM identifiers:
        ///
        ///   PUBLIC &quot;-//W3C//DTD XHTML 1.0 Frameset//EN&quot;
        ///   SYSTEM &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-fr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xhtml1_frameset {
            get {
                return ResourceManager.GetString("xhtml1_frameset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///   Extensible HTML version 1.0 Strict DTD
        ///
        ///   This is the same as HTML 4 Strict except for
        ///   changes due to the differences between XML and SGML.
        ///
        ///   Namespace = http://www.w3.org/1999/xhtml
        ///
        ///   For further information, see: http://www.w3.org/TR/xhtml1
        ///
        ///   Copyright (c) 1998-2002 W3C (MIT, INRIA, Keio),
        ///   All Rights Reserved. 
        ///
        ///   This DTD module is identified by the PUBLIC and SYSTEM identifiers:
        ///
        ///   PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot;
        ///   SYSTEM &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xhtml1_strict {
            get {
                return ResourceManager.GetString("xhtml1_strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///   Extensible HTML version 1.0 Transitional DTD
        ///
        ///   This is the same as HTML 4 Transitional except for
        ///   changes due to the differences between XML and SGML.
        ///
        ///   Namespace = http://www.w3.org/1999/xhtml
        ///
        ///   For further information, see: http://www.w3.org/TR/xhtml1
        ///
        ///   Copyright (c) 1998-2002 W3C (MIT, INRIA, Keio),
        ///   All Rights Reserved. 
        ///
        ///   This DTD module is identified by the PUBLIC and SYSTEM identifiers:
        ///
        ///   PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
        ///   SYSTEM &quot;http://www.w3.org/TR/xhtml1/D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xhtml1_transitional {
            get {
                return ResourceManager.GetString("xhtml1_transitional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ....................................................................... --&gt;
        ///&lt;!-- XHTML 1.1 DTD  ........................................................ --&gt;
        ///&lt;!-- file: xhtml11.dtd
        ///--&gt;
        ///
        ///&lt;!-- XHTML 1.1 DTD
        ///
        ///     This is XHTML, a reformulation of HTML as a modular XML application.
        ///
        ///     The Extensible HyperText Markup Language (XHTML)
        ///     Copyright 1998-2008 World Wide Web Consortium
        ///        (Massachusetts Institute of Technology, European Research Consortium
        ///         for Informatics and Math [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xhtml11 {
            get {
                return ResourceManager.GetString("xhtml11", resourceCulture);
            }
        }
    }
}
